weekly_playlist = ["Blinding Lights", "Levitating", "As It Was", "Heat Waves","Good 4 u"]

print("I will add a new song to your list: Drivers License")
weekly_playlist.append("Drivers License")
print("I will add at the beginning of your playlist: Bohemian Rhapsody")
weekly_playlist.insert(0, "Bohemian Rhapsody")
print(weekly_playlist)
print("You´ve been playing Good 4 u often, I´m going to delete it from your playlist")
weekly_playlist.remove("Good 4 u")
print("Levitating is at posotion: ")
weekly_playlist.index("Levitating")
print("You have Harry Styles:")
weekly_playlist.count("As It Was")
print(weekly_playlist)
new_playlist = weekly_playlist.copy()
print("Now time to reverse the playlist!")
new_playlist.reverse()
print(new_playlist)
nnew_playlist = weekly_playlist.copy()
print("Time to order it alphabetically")
nnew_playlist.sort()
print(nnew_playlist)